export { default as Cities } from './Cities'
export { default as Maps } from './Maps'
export { default as Header } from './Header'
export { default as People } from './People'
export { default as News } from './News'
export { default as Login } from './Login'
export { default as AdAdmin } from './AdAdmin'