export { default as AuthAction } from './auth'
export { default as NotifiAction } from './notification'
export { default as routeAction } from './routeMap'
export { default as peopleAction } from './people'
export { default as newsAction } from './news'
export { default as adAction } from './ad'
