export { default as auth } from './auth'
export { default as notification } from './notification'
export { default as routeMap } from './routeMap'
export { default as attachments } from './attachments'
export { default as people } from './people'
export { default as news } from './news'