export { default as Home } from './Home'
export { default as About } from './About'
export { default as Cities } from './Cities'
export { default as News } from './News'
export { default as Donuzlav } from './Donuzlav'
export { default as Manager } from './Manager'
export { default as City } from './City'